openapi: 3.0.0
info:
  title: Chatbot Enhancements API
  version: 1.0.0
paths:
  /tasks:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '409':
          description: Duplicate task found
  /users/me/stats:
    get:
      summary: Get user statistics
      responses:
        '200':
          description: User statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserStats'
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '401':
          description: Unauthorized
  /auth/logout:
    post:
      summary: User logout
      responses:
        '200':
          description: Logout successful
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
    TaskCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
    UserStats:
      type: object
      properties:
        open_tasks:
          type: integer
        completed_tasks:
          type: integer
        total_conversations:
          type: integer
    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    Session:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
